#!/bin/bash

if [ $EUID -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

su - postgres -c 'createuser -S -D -R koji' &> /dev/null
su - postgres -c 'createdb -O koji koji' &> /dev/null
useradd koji &> /dev/null
passwd -d koji &> /dev/null
su - koji -c 'psql koji koji < /usr/share/doc/koji*/docs/schema.sql' &> /dev/null
