#!/bin/bash

CANAME=koji
DN=/C=US/ST=Utah/L=Murray/O=GoOSe Project/CN=me3/emailAddress=admin@egavas.org

openssl genrsa -out private/${CANAME}_ca_cert.key 2048
openssl req -config ssl.cnf -new -x509 -days 3650 -key private/${CANAME}_ca_cert.key -subj "${DN}" -out ${CANAME}_ca_cert.crt -extensions v3_ca
