#!/bin/bash -x

CANAME=koji
DN='/C=US/ST=Utah/L=Murray/O=GoOSe Project/CN=koji2.egavas.org/emailAddress=admin@egavas.org'

openssl genrsa -out /etc/pki/koji/private/${CANAME}_ca_cert.key 2048
openssl req -config /etc/pki/koji/ssl.cnf -new -x509 -days 3650 -key /etc/pki/koji/private/${CANAME}_ca_cert.key -out /etc/pki/koji/${CANAME}_ca_cert.crt -subj "${DN}" -extensions v3_ca
